name: Update the combo list
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  mkcombo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Build
      run: |
        echo Debugging output
        uname
        pip3 --version
        pip3 list
        python --version
        which python
        id
        
        echo make the list
        pip3 install requests publicsuffixlist
        python combo.py
    - name: Commit & Push
      run: |
        git config user.name "Update bot"
        git config user.email "updatebot@naveenpnair.github.io"
        git add .
        git diff --staged --quiet || git commit -m "Update the combo list"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main